### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by comtaler** [robertdebock/ansible-role-rundeck#12]
Thanks for making such a great role for ansible, it will be better if it supports configuring database as well.

## Proposed feature

Allow configuring mysql or other type of database for storage

## Rationale

Should be able to configure:
dataSource.url
dataSource.driverClassName
dataSource.username
dataSource.password
rundeck.projectsStorageType

or other db related configs

## Additional context
None

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
Sounds like a plan, I'll give this attention, thanks!

**Comment by robertdebock** [comment]
Okay, this seems doable, I need to change a few things, but it will boil down to setting these variables:

```yaml
rundeck_config:
  - parameter: server.address
    value: "{{ rundeck_address }}"
  - parameter: grails.serverURL
    value: "{{ rundeck_url }}"
#   To connect to MySQL, use these settings. (Database has to be prepared.)
  - parameter: dataSource.url
    value: "jdbc:mysql://myserver/rundeck?autoReconnect=true&useSSL=false"
  - parameter: dataSource.username
    value: rundeck
  - parameter: dataSource.password
    value: rundeck
  - parameter:  #dataSource.driverClassName
    value: com.mysql.jdbc.Driver
```

Be aware the the MySQL database need to be prepared, you could use [robertdebock.mysql](https://galaxy.ansible.com/robertdebock/mysql). The `README.md` contains details how to setup databases, users and passwords.

I need some time to test this, maybe this mysql jdbc driver needs to be installed or so.

Anyway, thanks for the request, I'll come back to it.

**Comment by robertdebock** [comment]
I've used this playbook to use MySQL:

```yaml
---
- name: converge
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
    - role: robertdebock.hostname
    - role: robertdebock.mysql
      mysql_databases:
        - name: rundeck
      mysql_users:
        - name: rundeck
          password: rundeck
          priv: "rundeck.*:ALL"
    - role: robertdebock.rundeck
      rundeck_address: "{{ ansible_default_ipv4.address }}"
      rundeck_config:
        - parameter: server.address
          value: "{{ rundeck_address }}"
        - parameter: grails.serverURL
          value: "{{ rundeck_url }}"
        - parameter: dataSource.url
          value: "jdbc:mysql://localhost/rundeck?autoReconnect=true&useSSL=false"
        - parameter: dataSource.username
          value: rundeck
        - parameter: dataSource.password
          value: rundeck
        - parameter: dataSource.driverClassName
          value: com.mysql.jdbc.Driver
```
