### ISSUE TITLE
Using `master` branch, the `notify` directive on a `block` is not compatible with ansible 2.10

### ISSUE THREAD

**Issue by rsicart** [robertdebock/ansible-role-rundeck#15]
## Describe the bug

Using `master` branch, the `notify` directive on a `block` is not compatible with ansible 2.10.

ansible 5.x is ok.

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```
$ molecule test --scenario-name default
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO     Running ansible-galaxy role install -vr requirements.yml --roles-path /root/.cache/ansible-compat/8eb343/roles
INFO     Set ANSIBLE_LIBRARY=/root/.cache/ansible-compat/8eb343/modules:/root/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/root/.cache/ansible-compat/8eb343/collections:/root/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/root/.cache/ansible-compat/8eb343/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
...
```

```yaml
---
- name: Converge
  hosts: all
  become: true
  vars:
...
    rundeck_version: "3.4.9"
    rundeck_release_date: 20211221
    rundeck_rdeckbase: /srv/rundeck
    rundeck_xmx: 1024
    rundeck_xms: 256
    rundeck_maxmetaspacesize: 128
    rundeck_port: 4444
    rundeck_address: "{{ ansible_ec2_public_ipv4 }}"
    rundeck_config:
      - parameter: server.address
        value: "0.0.0.0"
      - parameter: server.port
        value: "{{ rundeck_port }}"
      - parameter: grails.serverURL
        value: "{{ rundeck_url }}"
    rundeck_framework:
      - parameter: framework.server.hostname
        value: "{{ ansible_ec2_public_ipv4 }}"
      - parameter: framework.server.name
        value: "{{ ansible_ec2_public_ipv4 }}"
  pre_tasks:
    - amazon.aws.ec2_metadata_facts:
  roles:
    - robertdebock.rundeck
```

## Output

Show at least the error, possible related output, maybe just all the output.

```
INFO     Running default > syntax
Molecule default > syntax 00:02
ERROR! 'notify' is not a valid attribute for a Block
The error appears to be in '/root/.cache/molecule/rundeck/default/roles/robertdebock.rundeck/tasks/main.yml': line 40, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: configure rundeck
  ^ here
CRITICAL Ansible return code was 4, command was: ['ansible-playbook', '--inventory', '/root/.cache/molecule/rundeck/default/inventory', '--skip-tags', 'molecule-notest,notest', '--syntax-check', '/builds/claranet/rmp/projects/ansible/rundeck/molecule/default/converge.yml']
```

## Environment

- Control node OS: Debian bullseye
- Control node Ansible version: 2.10.17
```
$ ansible --version
ansible 2.10.17
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.10.4 (main, Apr 20 2022, 05:30:59) [GCC 10.2.1 20210110]
$ molecule --version
molecule 3.5.2 using python 3.10 
    ansible:2.10.17
    delegated:3.5.2 from molecule
    ec2:0.4 from molecule_ec2
```
- Managed node OS: Debian buster

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
