### ISSUE TITLE
The admin user cannot access the plugin on the GUI

### ISSUE THREAD

**Issue by wouterdt** [robertdebock/ansible-role-rundeck#16]
## Descriptions

The plugins menu is not visible for the default admin user on the rundeck GUI.
It becomes visible when admin recieves wildcard privileges on the rundeck context in admin.aclpolicy 

`2022-09-26T14:59:19,027] WARN  authorization.LoggingAuthorization - Evaluating Decision for: res<type:resource, kind:plugin> subject<Username:admin Group:admin Group:user> action<read> env<rundeck:auth:env:application:rundeck>: authorized: false: REJECTED, reason: REJECTED, evaluations:        ACLRule</opt/rundeck/etc/admin.aclpolicy[2][type:resource][rule: 2]>{'Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.' context={application='rundeck'} type='resource' equals , resource={kind=system} for: { group='admin'} allow=[read, enable_executions, admin, disable_executions]} REJECTED for action read => REJECTED (0ms)
[2022-09-26T14:59:19,028] WARN  authorization.LoggingAuthorization - Evaluating Decision for: res<type:resource, kind:plugin> subject<Username:admin Group:admin Group:user> action<admin> env<rundeck:auth:env:application:rundeck>: authorized: false: REJECTED, reason: REJECTED, evaluations:       ACLRule</opt/rundeck/etc/admin.aclpolicy[2][type:resource][rule: 2]>{'Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.' context={application='rundeck'} type='resource' equals , resource={kind=system} for: { group='admin'} allow=[read, enable_executions, admin, disable_executions]} REJECTED for action admin => REJECTED (0ms)
[2022-09-26T14:59:19,029] WARN  authorization.LoggingAuthorization - Evaluating Decision for: res<type:resource, kind:plugin> subject<Username:admin Group:admin Group:user> action<install> env<rundeck:auth:env:application:rundeck>: authorized: false: REJECTED, reason: REJECTED, evaluations:     ACLRule</opt/rundeck/etc/admin.aclpolicy[2][type:resource][rule: 2]>{'Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.' context={application='rundeck'} type='resource' equals , resource={kind=system} for: { group='admin'} allow=[read, enable_executions, admin, disable_executions]} REJECTED for action install => REJECTED (0ms)
[2022-09-26T14:59:19,030] WARN  authorization.LoggingAuthorization - Evaluating Decision for: res<type:resource, kind:plugin> subject<Username:admin Group:admin Group:user> action<admin> env<rundeck:auth:env:application:rundeck>: authorized: false: REJECTED, reason: REJECTED, evaluations:       ACLRule</opt/rundeck/etc/admin.aclpolicy[2][type:resource][rule: 2]>{'Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.' context={application='rundeck'} type='resource' equals , resource={kind=system} for: { group='admin'} allow=[read, enable_executions, admin, disable_executions]} REJECTED for action admin => REJECTED (0ms)
`

```yaml
description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin

```
like over [here](https://github.com/jjethwa/rundeck/blob/master/content/opt/rundeck-defaults/admin.aclpolicy)

## Playbook

```yaml
- hosts: localhost
  become: true
  roles:
    - geerlingguy.java
    - robertdebock.rundeck

```

## Output

No error, admin  configuration file is missing privileges.

## Environment

- Control node OS: Red Hat Enterprise Linux release 8.6 (Ootpa) (`cat /etc/os-release`)
- Managed node OS:Red Hat Enterprise Linux release 8.6 (Ootpa) `cat /etc/os-release`)
