### ISSUE TITLE
URL is redirecting to local ip

### ISSUE THREAD

**Issue by Djrohith** [robertdebock/ansible-role-rundeck#6]
Hi 
once everything is installed and once i open the url with the specific public ip of that machine along with port 4440 it;s opening rundeck page for login details,but once i login it redirecting me to local ip 127.0.0.1 and says "this site cannot be reached"

please help me out what is issue is?
thanks in advance

**Describe the bug**

**To Reproduce**
1. Run this role:
2. See error

**Expected behavior**

**Error**
Please show the resulting error. If applicable a snippet of the playbook including the role ran with `-vvv`

**Environment**
- Control node OS: [e.g. Debian 9]
- Control node Ansible version: [e.g. 2.6.2]
- Managed node OS: [e.g. CentOS 7]

**Additional context**

**Comment by robertdebock** [comment]
I'll try to reproduce and update you on the progress, thanks @Djrohith!

**Comment by robertdebock** [comment]
You are correct. I'll change a variable and push in a moment.

Meanwhile you can use this playbook to overcome the problem:
```
---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  vars:
    rundeck_address: "{{ ansible_default_ipv4.address }}"

  roles:
    - robertdebock.bootstrap
    - robertdebock.java
    - robertdebock.rundeck
```
